FROM node:12.4.0-alpine AS builder

WORKDIR /usr/src/app/client
COPY package-lock.json .
COPY package.json .
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm ci \
    && npm install react-scripts@2.1.8 -g --silent \
    && apk del .gyp
COPY . .
RUN npm run build

FROM node:12.4.0-alpine

RUN npm install -g serve
COPY --from=builder /usr/src/app/client/build .
COPY --from=builder /usr/src/app/client/public .
CMD [ "serve", "-s", "build" ]
